base_url = "https://example.com"
languageCode = "en-us"
title = "Zola example"
# theme = "cactus"
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
compile_sass = true
highlight_code = true
build_search_index = false
generate_feed = true
# summaryLength = 2
description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."

paginate_by = 5

taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "categories", feed = true, paginate_by = 5 },
]

[extra]
damn = false
custom_css = ""
showProjectsList = true # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/gohugoio" # title link for projects list
copyright = "You" # cactus will use title if copyright is not set
date_format="%Y-%m-%d"
showAllPostsArchive = false # default
# Home page settings
mainSection = "posts" # your main section
showAllPostsOnHomePage = false # default
postsOnHomePage = 6 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = true # show tags overview by default.
ShowAllPostsOnHomePage = false
toc = true
rss = true # generate rss feed. default value is false
# googleAnalytics = "UA-1234-5"
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default
# Post page settings
show_updated = false # default
showReadTime = false # default
# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands

# Main menu which appears below site header.
[[extra.menu.main]]
name = "Home"
url = "/"
weight = 1

[[extra.menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[extra.menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[extra.menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[extra.menu.main]]
name = "About"
url = "/about"
weight = 5

[[extra.projects]]
name = "Hugo"
url = "https://gohugo.io/"
desc = "The world’s fastest framework for building websites."

[[extra.projects]]
name = "Hugo Themes"
url = "https://github.com/gohugoio/hugoThemes"
desc = "A curated directory of Hugo themes"

[[extra.social]]
  name = "github"
  link = "https://github.com/gohugoio"
[[extra.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/company/github/"
[[extra.social]]
  name = "email"
  link = "example@example.com"  # no need for "mailto:" in the head

[extra.comments]
  enabled = true # default
  engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
[extra.comments.utterances]
  repo = "<github_username>/<github_reponame>"
  label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
  theme = "github-light"
[extra.comments.cactuscomments]
  siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
  #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
  #serverName = "" # Defaults to cactus.chat

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
smart_punctuation = true
highlight_theme = "dracula"
